### ISSUE TITLE
Muting / moderation

### ISSUE THREAD

**Issue by noamross** [coatless-quarto/bluesky-comments#1]
Looking at the large number of 📌 replies in the [example](https://quarto.thecoatlessprofessor.com/bluesky-comments/qbluesky-comments-examples.html), it occurs to me that one probably wants some kind of moderation controls on this.

**Describe the solution you'd like**
A "client-side" or muting like approach would be to enable some kind of filtering by content or metadata.  A file in the site source, listing words, regexes, and/or people to mute, could pass this info to the JS that fetches the comments and filters those things out.

**Describe alternatives you've considered**
An AT-native moderation approach probably would require your site to have some kind of AT identity so that moderation tools could be used - e.g., blocking users from interacting with posts from the site.

**Comment by coatless** [comment]
Agreed, it would be nice to have. On the AT moderation tools, I think that relies upon a login to access via [`app.bsky.actor.getPreferences`](https://docs.bsky.app/docs/api/app-bsky-actor-get-preferences), which this is setup to avoid given the static nature of deployments. 

There are two approaches that I can implement to address it:

1. Each post currently has a `labels` attribute that I think contains different kinds of flags (spam/nsfw/trigger/???)
2. A filtering system built into `_quarto.yml` like: 

```yml
bluesky-comments:
  mute-patterns: 
    - "📌"
    - "🔥"
    - "spam"
  muted-users:
    - "did:plc:someuserdid123"
    - "did:plc:anotheruserdid456"
  filter-empty-replies: true
  default-visible: 5
```

The configuration options listed are:

- `mute-patterns`: Array of strings or patterns to filter out
- `muted-users`: Array of Bluesky DIDs to mute by default
- `filter-empty-replies`: Boolean to control filtering of empty/spam replies
- `default-visible`: Number of comments to show initially before "Show more"

Thoughts?
